name: himage
description: himage
version: 0.6.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  built_value:
  built_collection:
  random_color: ^1.0.3
  path_provider:
  path:
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  flutter_imagenetwork:
  video_box: ^0.15.1
  permission_handler:
  gradient_text: ^1.0.2
  webview_flutter:
  toast:
  file_picker:
  url_launcher: ^5.7.5
  ajanuw_http: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:
  mobx_codegen:

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
